name: Github Actions

on:
  push:
    branches:
      - master

jobs:
  my-job-1:
    runs-on: ubuntu-latest

    steps:
      - name: HI HELLO
        run: echo "Hello master2 !!!!"

      - name: HI HELLO2
        run: | 
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          
        

