name: Github Actions

on:
  push:
    branches:
      - master

jobs:
  my-job-1:
    runs-on: ubuntu-latest

    steps:
      - name: HI HELLO88
        run: echo "Hello master2222 !!!!"

      - name: HI HELLO2
        run: | 
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY

      - name: none display
        run: |
          echo ${{ secrets.MY_NAME }}
        
          
        

