name: Github Actions

on:
  push:
    branches:
      - master

jobs:
  my-job-1:
    runs-on: ubuntu-latest

    steps:
      - name: HI HELLO
        run: echo "Hello master2 !!!!"

      - name: HI HELLO22
        run: echo "Hello master2222 !!!!"

  my-job-2:
    runs-on: ubuntu-latest

    steps:
      - name: HI HELLO
        run: echo "Hello master2 !!!!"

      - name: HI HELLO22
        run: echo "Hello master2222 !!!!"

